branches:
  only:
  - master
language: node_js

# v14/stable(2020-05) produces empty html https://github.com/hexojs/hexo/issues/4257
node_js:
    - 'v13.8.0'

cache: npm

before_install:
- git config --global user.name "lizhuobin"
- git config --global user.email lzb383551179@gmail.com

install:
- npm install hexo-cli -g
- npm install

script:
- hexo clean
- hexo g

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: gh-pages
